### ISSUE TITLE
iai_kinect2: can't find cv_bridge

### ISSUE THREAD

**Issue by gavanderhoorn** [jonazpiazu/docker_images#1]
Trying to build the `iai_kinect2` image results in these errors at [this line](https://github.com/jonazpiazu/docker_images/blob/1a58fceb0ae22319d1e2e8f955f114fc87d28e9a/iai_kinect2/Dockerfile#L28-L35):

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
kinect2_viewer: Cannot locate rosdep definition for [cv_bridge]
kinect2_registration: Cannot locate rosdep definition for [cv_bridge]
iai_kinect2: Cannot locate rosdep definition for [catkin]
kinect2_calibration: Cannot locate rosdep definition for [cv_bridge]
kinect2_bridge: Cannot locate rosdep definition for [cv_bridge]
```

Not sure why though: `rosdep` db is successfully updated right before and `cv_bridge` isn't even a system dependency.

Any ideas?

**Comment by jonazpiazu** [comment]
There is actually a `cv_bridge` dependency in [kinect2_bridge](https://github.com/code-iai/iai_kinect2/blob/master/kinect2_bridge/package.xml#L22). 

Not sure anyway why you have that `rosdep` error, as the package `ros-indigo-cv-bridge` is in the `apt` list.

I will try to take a look at it.

**Comment by miguelprada** [comment]
You probably need to pass `--include-eol-distros` to `rosdep update`.

**Comment by jonazpiazu** [comment]
When running `rosdep update`:

```
Skip end-of-life distro "indigo"
```

So probably @miguelprada  is right.

**Comment by jonazpiazu** [comment]
See [the relevant commit](https://github.com/jonazpiazu/docker_images/commit/54ee3a4abf5cc00ad75f0cdedfc85db76a29151e) and the [automated build](https://cloud.docker.com/repository/registry-1.docker.io/jonazpiazu/iai_kinect2/builds/834e1691-7565-416c-af0f-ef0df67e7bea)

**Comment by gavanderhoorn** [comment]
Ah yes, thanks guys.

I was in a bit of a hurry, so didn't think about the EOL status of Indigo ;)

Thanks for fixing it so quickly :+1:
